{% set name = "lesscpy" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ef058fb3fca077f0136222c415bc6d20fe256e92648ccbf4b3de874ba03b9b9d

build:
  noarch: python
  entry_points:
    - lesscpy = lesscpy.scripts.compiler:run
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools

  run:
    - python >=3.6
    - ply
    - six

test:
  imports:
    - lesscpy
    - lesscpy.lessc
    - lesscpy.lib
    - lesscpy.plib
    - lesscpy.scripts

  commands:
    - lesscpy --help
    - pip check

  requires:
    - pip

about:
  home: https://github.com/lesscpy/lesscpy
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Python LESS compiler
  dev_url: https://github.com/lesscpy/lesscpy

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
