{% set name = "lesscpy" %}
{% set version = "0.13.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "f3c6d0b544c5bcdadcd3d8319feccb4128d06676d4117c6c9396ab39c25372ad" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}

build:
  entry_points:
    - lesscpy = lesscpy.scripts.compiler:run
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - ply
    - six

test:
  imports:
    - lesscpy
    - lesscpy.lessc
    - lesscpy.lib
    - lesscpy.plib
    - lesscpy.scripts

  commands:
    - lesscpy --help

about:
  home: https://github.com/lesscpy/lesscpy
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'Python LESS compiler'
  dev_url: https://github.com/lesscpy/lesscpy

extra:
  recipe-maintainers:
    - pmlandwehr
