travis:
  secure:
    BINSTAR_TOKEN: lcVadBw3q0NQgHkSDyNmARcARFgNuvAHu4XjG4Od+dVd6oPtItogujIXg2iCFyZ5vNvijbVmOtYz4vMOKp51p/rXOeyPJHcoElNWR/gBDHThN4eA+S8Sk6EGSui0uon4Hu1ClleIiWGYSwiTDZWm/65sKz+f9mFCLWk/A8/RVmaKQCl92aLqfC1Fz8HK2YXT0adAAe5+WkxPB7ZvGlhH2ZHRcv9Buk5CkbRhECP5v90seP1WvR2TkrmMODRc14PTUiPOrKpTDIQR+d1AAA3nYTtYiiCAP3mNDV7Jp4V2bgc6biXcqNn1JC5paYSsSEb8urfnhnwDE/lnbWto/G+CPmVnmfacUUnxDZvXLEqbn8Nn3392pqRK1lNQTmvRemtsxzsPHwcZ1GDosZcCy5K1/pXUoEI5CFm3OkRd6fXKTzS0aqTDLMwljHwRsK/kVAk1/9bSROsZMm/33b4l5hq8lPA9V2BV0J9kvz9izuWfDu1huK4mjWn/OhxqCMSBeeGNb34isaYZL/bCu7V1SMICYvYTE48fNca7e6Ud0NBRlGZGdpAsR0d1fjSEVOBpawYsw6NRVwSO0vkZpgXMvP46grRm+3sf/PHYgTP+xYmuLR+0fXA1yjzr1CdpygjTB12JOH9S4VruZn83t46BT7izT04VH8DWWBxBBxFyhYwLSEs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
