travis:
  secure:
    BINSTAR_TOKEN: NIab5Qsk5CSJezdwrfKsQ1ySp/PG5yb1eKurloLUY62rthvKQ4YZRqR1v5/qhDDfllzOjge4CTTuRGYtbp0esJC8l3FKiN7bSU1FWrS27HjerWuPlzoS4B33hKb15dIRxLPpVxhoYUKOLrxFjY/qAj03tXKgusqyNUzMjB+61l0x9pdWqtL9srOeIpCCJyXsy9UVSWeLGRW0T084rwrqwzjnaEiyWfyCbET7A9cG2x6UAsbNbcDOI80GouLr8DHWYMCtdgp4Z70IDJ24X/wQQuMgSJ8Y2dUQIco1t6GDjB7IgftIbsVTnhWmqamS4tpYakIibpfA8Cmvfqd0/iy+DO0S6AkxRzdBEdqi1z7FndiX2JvG8XAActx5xxHOFzaRwPUJ9C5zGTdjrYtoN1Sik+wjOJvdfQj0siHR0QXd+2aSJyfNXUBsIoDggSkFHtOYlz7MTtWR2tYHfMvqT34zSpqwoJzkdmifQYeCwGslgOxdNI2zdGcE7v9/hJW8zqgFlkAjhS0ccClPnRX+VB6xQatJnM2O5BNuCluSpZd8kHMva4ddrffO1IgI4Dwsn15vvpbZO78t207YgN5s8lbGdeuzQ9zCLMZXHigTfHnV1xdiKoaOppthp6WK8muaWm+H+EvsxrkQlLzc6XYNFmlHA473PF5bbGsa+jFtcqtcljw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
